# version: "3"
# services:
#   database:
#     image: "postgres:latest"
#     ports:
#       - 5432:5432
#     env_file:
#       - .env
#     environment:
#       - POSTGRES_DB=default_database produtos_db

services:
  db:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: produtos_user
      POSTGRES_PASSWORD: admin_produtos
      POSTGRES_DB: produtos_db
    ports:
      - "5432:5432"
    # networks:
    #   - db
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
networks:
  db:
    driver: bridge
